---
- name: Create a generic driver for docker-machine
  local_action: command docker-machine create \
    --driver=generic \
    --generic-ip-address={{ansible_host}} \
    --generic-ssh-user=dockermachine \
    --generic-ssh-key={{dockermachine_ssh_private_key_file}} \
    --generic-ssh-port={{ansible_port}} \
    {{inventory_hostname}}
