---
- name: test default ssh port
  local_action: wait_for port=22 timeout=5 host={{inventory_hostname}}
  register: default_ssh
  ignore_errors: true

- name: set ansible_ssh_port to default
  set_fact: ansible_ssh_port=22
  when: default_ssh.elapsed < 5

- name: test ssh on high port
  local_action: wait_for port={{custom_ssh_port}} timeout=5 host={{inventory_hostname}}
  register: high_ssh
  when: default_ssh.elapsed >= 5
  ignore_errors: true

- name: set ansible_ssh_port high
  set_fact: ansible_ssh_port={{custom_ssh_port}}
  when: default_ssh.elapsed >= 5 and high_ssh.elapsed < 5

- name: Change the port in SSHd Config only if default port still configured
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 22" line="Port {{custom_ssh_port}}" state=present
  when: default_ssh.elapsed < 5 and high_ssh.elapsed >= 5
  notify: restart ssh
  tags:
    - sshd.config.port.change
