---

- name: Change the port in SSHd Config only if default port still configured
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 22" line="Port {{custom_ssh_port}}" state=present
  when: default_ssh.elapsed < 5 and high_ssh.elapsed >= 5
  notify: restart ssh
  tags:
    - sshd.config.port.change

- name: set ansible_port high in case the SSHd Config has been changed to use the custom port
  set_fact: ansible_port={{custom_ssh_port}}
  when: default_ssh.elapsed >= 5 and high_ssh.elapsed < 5
  tags:
    - sshd.config.port.set_custom
