---
- name: create a webapp directory on the host machine
  file: name=/etc/docker/webapp state=directory

- name: deploy the docker-compose file onto the host machine
  copy: src={{webapp_compose_path}}/docker-compose.yml dest=/etc/docker/webapp/docker-compose.yml

- name: update the image for the web app if it has changed
  command: docker-compose -f /etc/docker/webapp/docker-compose.yml pull web

- name: instantiate a new instance of the web application and its database
  docker_service: project_src=/etc/docker/webapp/ state=present
