---
- name: Install pre-requisites
  apt: name=apt-transport-https update_cache=yes

- name: Install pre-requisites
  apt: name=ca-certificates

- name: Add GPG key for the official Apt repository for Docker
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Create a file for Docker repository in APT sources directory
  file: path=/etc/apt/sources.list.d/docker.list state=touch mode="u=rw,g=r,o=r"

- name: checking the current release of ubuntu so we can use the approproriate repo for docker
  command: lsb_release -cs
  register: codename

- name: Add remote package repository in APT sources for Docker (xenial)
  lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-xenial main"
  when: codename.stdout == 'xenial'

- name: Add remote package repository in APT sources for Docker (trusty)
  lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
  when: codename.stdout == 'trusty'

- name: Update the package database with the Docker packages from the newly added repo
  apt: update_cache=yes

- name: Make sure we install from the Docker repo instead of the default Ubuntu 16.04 repo
  command: apt-cache policy docker-engine
  register: apt_cache_policy

- name: Install Docker Engine
  apt: name=docker-engine
  when: apt_cache_policy.stdout.find('apt.dockerproject.org')

- name: Install python-pip needed to install docker-py
  apt: name=python-pip

- name: Install docker-py for managing containers with docker_service module
  command: pip install docker-py

- name: Install docker-compose for managing containers with docker_service module
  command: pip install docker-compose
