---
# This playbook configure hosts: initial configuration, installing docker on  non DO hosts


- name: apply initial common configuration to all hosts
  hosts: all
  gather_facts: false
  vars:
    - custom_ssh_port: "{{custom_port}}"
  vars_files:
    - ../private_vars/ssh_connect.yml

  roles:
    - { role: ssh_user_detect, tags: ["hostconfig", "ssh_user_detect"] }
    - { role: ssh_port_detect, tags: ["hostconfig", "ssh_port_detect"] }
    - { role: python, tags: ["hostconfig","python"] }
    - { role: sshd, tags: ["hostconfig", "sshd"] }
    - { role: swap, tags: ["hostconfig", "swap"] }
    - { role: ufw,  tags: ["hostconfig", "ufw"] }


- name: set up docker daemon
  hosts: all
  gather_facts: false
  vars_files:
  - ../private_vars/ssh_connect.yml
  vars:
    - ansible_port: "{{custom_port}}"

  roles:
    - { role: ssh_user_detect, tags: ["docker", "ssh_user_detect"] }
    - { role: dockerd, tags: ["docker"] }

- name: remove root access
  hosts: all
  gather_facts: false
  vars_files:
  - ../private_vars/ssh_connect.yml
  vars:
    - ansible_port: "{{custom_port}}"

  roles:
    - { role: ssh_user_detect, tags: ["deroot", "ssh_user_detect"] }
    - { role: deroot, tags: ["deroot"] }
